name: openclaw

on:
  workflow_dispatch:
  schedule:
    - cron: "45 7 * * 0"


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config/Dockerfile Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: zarguell/auto_container_builds
          path: config-repo
      
      - name: Checkout OpenClaw Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: openclaw/openclaw
          ref: v2026.2.1  # or lock to a stable tag like '2026.1.30' for safety
          path: openclaw-src

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      -
        name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (MAIN)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./openclaw-src
          file: ./config-repo/dockerfiles/openclaw.Dockerfile 
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openclaw:latest